version: '3'
services:
  cronjob:
    container_name: covid19-web_crawler-dev
    build: .
    restart: unless-stopped
    env_file:
      - docker/env/crawler.env
    environment:
      HOST_IP: covid19-backend-dev
    volumes:
      - ./logs:/app/logs
    networks:
      - covid19-backend-dev

networks:
  covid19-backend-dev:
    external: true
